### ISSUE TITLE
Issue with org-reverse-datetree-goto-read-date-in-file

### ISSUE THREAD

**Issue by krayF1sh** [akirak/org-reverse-datetree#16]
Hello,
I have created a capture template `("d" "Daily Plan" plain (file+function "~/path/to/org/file" org-reverse-datetree-goto-read-date-in-file) "Today\n- [ ]\n- [ ]\n- [ ]\n==========\nMaybe Today\n- [ ]\n==========\nNew Ideas - Tasks\n- [ ]\n\nEntered on %U %i %a%?" :prepend t)`.

When trying to use it it returns `org-capture-set-target-location: Symbol’s function definition is void: org-reverse-datetree-goto-read-date-in-file`.

But if instead I change the template `org-reverse-datetree-goto-read-date-in-file` to `org-reverse-datetree-goto-date-in-file`, run once, and then change these functions again it works properly.

In addition, if I don't run first the `org-reverse-datetree-goto-date-in-file` then the `org-reverse-datetree-goto-read-date-in-file` doesn't appear when hitting `M-x` or `C-h-f`.

**Comment by akirak** [comment]
Thank you for catching this. I think I have fixed the issue. If it hasn't, please feel free to reopen the issue.

**Comment by krayF1sh** [comment]
Hey, thank you for the fast response. It seems like it isn't fixed. I have run `package-refresh-content` also but remains the same.
![Screenshot from 2021-06-01 08-30-21](https://user-images.githubusercontent.com/42109143/120271489-1ceb0c00-c2b4-11eb-8020-929e75b6069e.png)

**Comment by akirak** [comment]
>  I have run `package-refresh-content` also but remains the same.

Hmm, did you install the latest version of the package? The fixed version is `20210531.1929` on MELPA, and it must have `;;;###autoload` annotation on the function.

**Comment by krayF1sh** [comment]
Sorry for that, I thought `package-refresh-content` updates the package to the new version. Now it's ok. Thank you and great job with this package.

**Comment by akirak** [comment]
Thanks, I'm glad to hear that.
